/**
* @author       : Ketan Arora
* @date         : 17/06/2018
* @description  : This is a util class used for reusing constant values.
*/
public without sharing class Util_Constants{


public static Final String  COMBOBOX_DEFALT_VALUE = '-- Select a value --';

//Exception Constansts
public static Final String  TOO_MANY_RECORDS = 'Too many records found';
public static Final String  EXCEPTION_CONSTANTS = 'Insufficient Privileges';

}